backend:
  name: git-gateway
  branch: main

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "collections"
    label: "Collections"
    folder: "content/collections"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Featured Image", name: "featured_image", widget: "image", required: false}
      - {label: "Collection Type", name: "collection_type", widget: "select", options: ["physical", "digital", "mixed"]}
      - {label: "Access Level", name: "access_level", widget: "select", options: ["public", "restricted", "private"]}
      - {label: "Metadata Schema", name: "metadata_schema", widget: "select", options: ["dublin_core", "custom"]}
      - {label: "Subjects", name: "subjects", widget: "list"}
      - {label: "Creators", name: "creators", widget: "list"}
      - {label: "Contributors", name: "contributors", widget: "list", required: false}
      - label: "Coverage"
        name: "coverage"
        widget: "object"
        fields:
          - {label: "Temporal", name: "temporal", widget: "string", required: false}
          - {label: "Spatial", name: "spatial", widget: "string", required: false}
      - {label: "Rights", name: "rights", widget: "select", options: ["Creative Commons Attribution 4.0", "Public Domain", "In Copyright", "Unknown"]}
      - {label: "Related Collections", name: "related_collections", widget: "relation", collection: "collections", searchFields: ["title"], valueField: "{{slug}}", displayFields: ["title"], multiple: true, required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - label: "SEO"
        name: "seo"
        widget: "object"
        fields:
          - {label: "Meta Description", name: "meta_description", widget: "text", required: false}
          - {label: "Keywords", name: "keywords", widget: "list", required: false}
          - {label: "Canonical URL", name: "canonical_url", widget: "string", required: false}

  - name: "items"
    label: "Items"
    folder: "content/items"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Identifier", name: "identifier", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Collection", name: "collection", widget: "relation", collection: "collections", searchFields: ["title"], valueField: "{{slug}}", displayFields: ["title"]}
      - {label: "Item Type", name: "item_type", widget: "select", options: ["image", "document", "audio", "video", "3d"]}
      - {label: "Format", name: "format", widget: "string"}
      - {label: "Featured Image", name: "featured_image", widget: "image", required: false}
      - label: "Access Files"
        name: "access_files"
        widget: "object"
        fields:
          - {label: "Thumbnail", name: "thumbnail", widget: "image", required: false}
          - {label: "Medium", name: "medium", widget: "file", required: false}
          - {label: "Large", name: "large", widget: "file", required: false}
          - {label: "Original", name: "original", widget: "file", required: false}
      - label: "Metadata"
        name: "metadata"
        widget: "object"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Creator", name: "creator", widget: "list"}
          - {label: "Subject", name: "subject", widget: "list"}
          - {label: "Description", name: "description", widget: "text"}
          - {label: "Publisher", name: "publisher", widget: "string", required: false}
          - {label: "Contributor", name: "contributor", widget: "list", required: false}
          - {label: "Date", name: "date", widget: "string", required: false}
          - {label: "Type", name: "type", widget: "string", required: false}
          - {label: "Format", name: "format", widget: "string", required: false}
          - {label: "Identifier", name: "identifier", widget: "string", required: false}
          - {label: "Source", name: "source", widget: "string", required: false}
          - {label: "Language", name: "language", widget: "select", options: ["en", "es", "fr", "de", "it", "pt", "zh", "ja", "ar"], default: "en"}
          - {label: "Relation", name: "relation", widget: "list", required: false}
          - {label: "Coverage", name: "coverage", widget: "string", required: false}
          - {label: "Rights", name: "rights", widget: "string", required: false}
          - label: "Dimensions"
            name: "dimensions"
            widget: "object"
            required: false
            fields:
              - {label: "Width", name: "width", widget: "number", required: false}
              - {label: "Height", name: "height", widget: "number", required: false}
              - {label: "Duration", name: "duration", widget: "string", required: false}
          - label: "Location"
            name: "location"
            widget: "object"
            required: false
            fields:
              - {label: "Place", name: "place", widget: "string", required: false}
              - {label: "Coordinates", name: "coordinates", widget: "string", required: false}
          - {label: "Provenance", name: "provenance", widget: "text", required: false}
          - {label: "Condition", name: "condition", widget: "select", options: ["Excellent", "Good", "Fair", "Poor"], required: false}
          - {label: "Transcription", name: "transcription", widget: "markdown", required: false}
      - label: "Technical Metadata"
        name: "technical_metadata"
        widget: "object"
        required: false
        fields:
          - {label: "File Size", name: "file_size", widget: "string", required: false}
          - {label: "MIME Type", name: "mime_type", widget: "string", required: false}
          - {label: "Checksum", name: "checksum", widget: "string", required: false}
          - {label: "Color Space", name: "color_space", widget: "string", required: false}
          - {label: "Resolution", name: "resolution", widget: "string", required: false}
      - {label: "Related Items", name: "related_items", widget: "relation", collection: "items", searchFields: ["title"], valueField: "{{slug}}", displayFields: ["title"], multiple: true, required: false}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "pages"
    label: "Pages"
    files:
      - file: "content/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}

      - file: "content/privacy/index.md"
        label: "Privacy Policy"
        name: "privacy"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}

      - file: "content/terms/index.md"
        label: "Terms of Use"
        name: "terms"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}